[package]
name = "hptp"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
    opt-level = 3
    strip = true
    lto = "fat"
    panic = "abort"
    codegen-units = 1
    incremental = false

[profile.dev]
    opt-level = 0
    incremental = true
    debug = true
    panic = "unwind"
    strip = false
    lto = "off"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
log = { version = "0.4.22" }
arrayvec = "0.7.4"
futures = "0.3.30"
rand = "0.9.0-alpha.1"
clap = { version = "4.5.8", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive"] }
smallvec = { version = "2.0.0-alpha.6", features = ["write"] }
itertools = "0.13.0"
hickory-resolver = "0.25.0-alpha.1"

[dependencies.simple_logger]
version = "5.0.0"
features = ["colors", "timestamps", "threads", "stderr"]